Ext.data.JsonP.env_ubuntu({
    "guide": [
        '<h1>Next JS 環境構築ガイド</h1>',
        '<h2>開発環境構築 - Ubuntu Server</h2>',
        '<p>',
        'まず、Ubuntu Serverをインストールする必要があります。',
        'ここでは、Ubuntu Server 10.04 LTS 32 bit を使ってインストール手順を紹介します。',
        '<a href="http://www.ubuntu.com/" target="_blank">ubuntu.com</a>からインストールイメージをダウンロードし準備してください。',
        'インストールを行うマシンはインターネットに接続されていてipアドレスはDHCPによる自動割当がされるものとして説明します。',
        '</p>',
        '<h3>インストール</h3>',
        '<p>',
        'ディスクを挿入して、サーバーを起動すると、次のような画面が表示されます。',
        '</p>',

        '<p><strong>Step.1</strong></p>',
        '<img src="pages/env_ubuntu/images/step01.jpg" />',
        '<p><em>日本語</em>を選択して進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.2</strong></p>',
        '<img src="pages/env_ubuntu/images/step02.jpg" />',
        '<p><em>Ubuntuサーバーをインストール</em>を選択して進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.3</strong></p>',
        '<img src="pages/env_ubuntu/images/step03.jpg" />',
        '<p>任意のキーボードを選択します。ここでは<em>Generic 105-ky (Intel) PC</em>を選びました。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.4</strong></p>',
        '<img src="pages/env_ubuntu/images/step04.jpg" />',
        '<p>キーボードレイアウトについての問い合わせです。手動で設定するよう<em>いいえ</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.5</strong></p>',
        '<img src="pages/env_ubuntu/images/step05.jpg" />',
        '<p><em>Japan</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.6</strong></p>',
        '<img src="pages/env_ubuntu/images/step06.jpg" />',
        '<p>レイアウトは<em>Japan</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.7</strong></p>',
        '<img src="pages/env_ubuntu/images/step07.jpg" />',
        '<p>任意のホスト名を入力します。入力後はTABキーを押し続けるを選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.8</strong></p>',
        '<img src="pages/env_ubuntu/images/step08.jpg" />',
        '<p>タイムゾーンがAsia/Tokyoでよろしければ<em>はい</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.9</strong></p>',
        '<img src="pages/env_ubuntu/images/step09.jpg" />',
        '<p>ディスクのパーティショニングです。規定値でよければそのまま進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.10</strong></p>',
        '<img src="pages/env_ubuntu/images/step10.jpg" />',
        '<p>ディスクを選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.11</strong></p>',
        '<img src="pages/env_ubuntu/images/step11.jpg" />',
        '<p>変更内容に問題がなければ<em>はい</em>を選び進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.12</strong></p>',
        '<img src="pages/env_ubuntu/images/step12.jpg" />',
        '<p>利用可能な容量を設定します。デフォルトでよければ<em>続ける</em>を選択し進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.13</strong></p>',
        '<img src="pages/env_ubuntu/images/step13.jpg" />',
        '<p>パーティショニングの設定内容に問題がなければ<em>はい</em>を選び次に進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.14</strong></p>',
        '<img src="pages/env_ubuntu/images/step14.jpg" />',
        '<p>ベースシステムのインストール中</p>',
        '<br /><br /><br />',

        '<p><strong>Step.15</strong></p>',
        '<img src="pages/env_ubuntu/images/step15.jpg" />',
        '<p>ユーザーの本名を入力して続けます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.16</strong></p>',
        '<img src="pages/env_ubuntu/images/step16.jpg" />',
        '<p>アカウント名を入力して進めます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.17</strong></p>',
        '<img src="pages/env_ubuntu/images/step17.jpg" />',
        '<p>パスワードを入力して進めます</p>',
        '<br /><br /><br />',

        '<p><strong>Step.18</strong></p>',
        '<img src="pages/env_ubuntu/images/step18.jpg" />',
        '<p>パスワードを再度入力して進めます</p>',
        '<br /><br /><br />',

        '<p><strong>Step.19</strong></p>',
        '<img src="pages/env_ubuntu/images/step19.jpg" />',
        '<p>暗号化の必要がなければ<em>いいえ</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.20</strong></p>',
        '<img src="pages/env_ubuntu/images/step20.jpg" />',
        '<p>プロキシ情報を入力し進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.21</strong></p>',
        '<img src="pages/env_ubuntu/images/step21.jpg" />',
        '<p>自動アップグレードを行わないように選択し進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step22.</strong></p>',
        '<img src="pages/env_ubuntu/images/step22.jpg" />',
        '<p>必要なソフトウェアを選択します。リモートログインができるよう<em>OpenSSH server</em>を選択します。選択はスペースキーで行います。選択が終わりましたら次へ進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step23.</strong></p>',
        '<img src="pages/env_ubuntu/images/step23.jpg" />',
        '<p>ブートローダーをインストールするため<em>はい</em>を選んで進みます。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.24</strong></p>',
        '<img src="pages/env_ubuntu/images/step24.jpg" />',
        '<p>インストール完了後、<em>続ける</em>を選んで進めシステムを再起動させます。インストール作業は以上です。</p>',
        '<br /><br /><br />',

        '<h3>インストール後の設定</h3>',
        '<p>インストール後のUbuntu Serverのターミナルは日本語を正しく表示できません。ここではメッセージを日本語ではなく英語で表示するよう設定します。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.25</strong></p>',
        '<img src="pages/env_ubuntu/images/step25.jpg" />',
        '<p>インストール時に設定したユーザー名とパスワードを入力しログインします。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.26</strong></p>',
        '<img src="pages/env_ubuntu/images/step26.jpg" />',
        '<p>ログイン完了</p>',
        '<br /><br /><br />',

        '<p><strong>Step.27</strong></p>',
        '<img src="pages/env_ubuntu/images/step27.jpg" />',
        '<p>nanoエディタを使い設定ファイルを編集します。ターミナルで以下のように入力してください。</p>',
        '<pre>nano .bashrc</pre>',
        '<br /><br /><br />',

        '<p><strong>Step.28</strong></p>',
        '<img src="pages/env_ubuntu/images/step28.jpg" />',
        '<p>nanoエディタが起動し設定ファイルが編集できます。設定ファイルの最後に以下の内容を記述します。</p>',
        '<pre>case $TERM in<br/>linux) LANG=C ;;<br/>*) LANG=ja_JP.UTF-8 ;;<br/>esac</pre>',
        '<br /><br /><br />',

        '<p><strong>Step.29</strong></p>',
        '<img src="pages/env_ubuntu/images/step29.jpg" />',
        '<p>入力後は<em>CTRL+O</em>で保存します。保存するファイル名は<em>.bashrc</em>です。Enterキーを押して保存します。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.30</strong></p>',
        '<img src="pages/env_ubuntu/images/step30.jpg" />',
        '<p>保存できたら<em>CTRL+X</em>を押しnanoエディタを終了します。</p>',
        '<br /><br /><br />',

        '<p><strong>Step.31</strong></p>',
        '<img src="pages/env_ubuntu/images/step31.jpg" />',
        '<p>設定が正しくできたかを確認します。ターミナルで<em>apt-get update</em>と入力します。この時点ではメッセージが文字化けしたまま表示されます。設定を反映させるため<em>source .bashrc</em>と入力します。再び<em>apt-get update</em>を実行するとメッセージが英語で表示されます。<br/><br/>以上でメッセージの設定は終了です。</p>',
        '<br /><br /><br />',


        '<h3>初期設定</h3>',
        '<p>',
        '無事インストールが完了したところで、これからはSSHで接続をして初期設定を行っていきます。',
        'ターミナルから(Windowsの場合PuttyやTeraTermなど)、SSHで接続を行います。',
        'Ubuntu Serverのipアドレスは<em>ifconfig</em>コマンドで確認してください。',
        'ここではipアドレスが<em>192.168.1.20</em>として説明します。',
        '</p>',
        '<pre>',
        'ssh <strong><アカウント名></strong>@192.168.1.20',
        '</pre>',
        '<p>',
        'インストール時に設定したパスワードでログインを行います。',
        '</p>',

        '<h3>パッケージのアップデート</h3>',
        '<p>',
        'まず、インストールされているパッケージを最新版にアップデートします。',
        'インターネットに接続されている必要がありますので、注意してください。',
        '</p>',
        '<pre>',
        'sudo apt-get update' + "\n",
        '</pre>',
        '<p>',
        'パスワードの問い合わせで自身のパスワードを入力します。',
        '</p>',

        '<h3>必要パッケージの追加</h3>',
        '<pre>',
        'sudo apt-get install git-core build-essential libssl-dev curl',
        '</pre>',

        '<h3>nave経由でnode.jsのインストール</h3>',
        '<p>',
        'naveを導入することで複数のnodeバージョンを簡単に切り替えて利用することができます。',
        'ここでは、最新版のnodeを0.5.5として設定を紹介していますが、必要に応じて最新版のバージョン番号に置き換えてください。',
        '</p>',

        '<h4>naveのインストール</h4>',
        '<pre>',
        'cd /usr/local/src' + "\n",
        'sudo git clone git://github.com/isaacs/nave.git' + "\n",
        'cd nave' + "\n",
        './nave.sh install latest' + "\n",
        '</pre>',

        '<h4>nodeを利用可能にする</h4>',
        '<pre>',
        'echo "/usr/local/src/nave/nave.sh use latest" >> ~/.bash_profile' + "\n",
        'source ~/.bash_profile' + "\n",
        '</pre>',
        '<p>',
        'メッセージにて',
        '<pre>',
        'Already installed: 0.5.5\nusing 0.5.5',
        '</pre>',
        'と表示されれば完了です。今後node.jsに更新があった場合は自動的に最新版となります。',
        '</p>',

        '<h3>npmのインストール</h3>',
        '<pre>',
        'curl http://npmjs.org/install.sh | sh',
        '</pre>',
        '<p>',
        '<em>Is this OK? enter \'yes\' or \'no\'</em>と聞かれたら<em>yes</em>を入力してエンターキーを押します。',
        '</p>',
        '<br />',

        '<h4>npmのバージョン確認</h4>',
        '<pre>',
        'npm -v' + "\n",
        '&gt; 1.0.27' + "\n",
        '</pre>',

        '<h3>Next JSのインストール</h3>',
        '<pre>',
        'cd' + "\n",
        'npm install nx',
        '</pre>',

        '<h3>Next JS動作確認</h3>',
        '<pre>',
        'cd' + "\n",
        'mkdir www' + "\n",
        'cd www' + "\n",
        'echo "require(\'nx\').service();" > server.js' + "\n",
        'mkdir public' + "\n",
        'echo "&lt;html&gt;\n&lt;head&gt;\n    &lt;title&gt;Next JS Test&lt;/title&gt;\n&lt;/head&gt;\n&lt;body&gt;\n    &lt;p&gt;Next JS Setting Complete.&lt;/p&gt;\n&lt;/body&gt;\n&lt;/html&gt;" > public/index.html' + "\n",
        'node server start;',
        '</pre>',
        '<p>ブラウザからアクセスして表示を確認します。</p>',
        '<pre>',
        'http://192.168.1.20:3000/',
        '</pre>',
        '<p>確認が終わったら、サーバーを停止します。</p>',
        '<pre>',
        'node server stop',
        '</pre>',
        '<br /><br /><br />',
        
        '<p>以上で環境の構築は終了です。</p>'

    ].join("")
});
