Ext.data.JsonP.tutorial_upload({
    "guide": [

        '<h1>ファイルアップロード</h1>',
        '<p>',
        'ファイルのアップロードは、標準のnodeでは利用できません。',
        'POST送信されたmultipart/form-dataを自前で解析する必要があるためです。',
        'Next JSでは、アクション内で簡単にアップロードされたファイルを処理することができます。',
        '</p>',

        '<h2>アップロードフォームの準備</h2>',
        '<p>',
        'まずは、ファイルをアップロードするためのフォームを準備します。',
        '</p>',

        '<h4>index.html</h4>',
        '<pre>',
        '<span style="color:#0000FF;">&lt;html&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;head&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;meta <span style="color:#000000;">http-equiv=</span><span style="color:#009900;">&quot;Content-Type&quot;</span> <span style="color:#000000;">content=</span><span style="color:#009900;">&quot;text/html; charset=utf8&quot;</span>&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;title&gt;</span>Next JS UPLOADテスト<span style="color:#0000FF;">&lt;/title&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/head&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;body&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;h2&gt;</span>Upload<span style="color:#0000FF;">&lt;/h2&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;form <span style="color:#000000;">action=</span><span style="color:#009900;">&quot;./upload.html&quot;</span> <span style="color:#000000;">method=</span><span style="color:#009900;">&quot;post&quot;</span> <span style="color:#000000;">enctype=</span><span style="color:#009900;">&quot;multipart/form-data&quot;</span>&gt;</span>' + "\n",
        '        ファイル：<span style="color:#0000FF;">&lt;br /&gt;</span>' + "\n",
        '        <span style="color:#0000FF;">&lt;input <span style="color:#000000;">type=</span><span style="color:#009900;">&quot;file&quot;</span> <span style="color:#000000;">name=</span><span style="color:#009900;">&quot;upfile&quot;</span> <span style="color:#000000;">size=</span><span style="color:#009900;">&quot;30&quot;</span> /&gt;</span><span style="color:#0000FF;">&lt;br /&gt;</span>' + "\n",
        '        <span style="color:#0000FF;">&lt;br /&gt;</span>' + "\n",
        '        <span style="color:#0000FF;">&lt;input <span style="color:#000000;">type=</span><span style="color:#009900;">&quot;submit&quot;</span> <span style="color:#000000;">value=</span><span style="color:#009900;">&quot;アップロード&quot;</span> /&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;/form&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/body&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/html&gt;</span>',
        '</pre>',

        '<h2>アップロード処理の実装</h2>',
        '<p>',
        '次に、アップロードされたときに処理をする部分を実装していきます。',
        '先ほどのフォームのリクエスト先は、<em>./upload.html</em>になっていました。',
        'つまり、<em>uploadアクション</em>が実行されることになりますので、actionsディレクトリ下に<em>upload.js</em>を配置します。',
        '</p>',

        '<h4>upload.js</h4>',
        '<pre>',
        'module.exports = [{' + "\n",
        '    execute: <span style="color:#000099;">function</span>() {' + "\n",
        '        <span style="color:#000099;">var</span> me = <span style="color:#000099;">this</span>;' + "\n",
        '        <span style="color:#000099;">var</span> upfile = me.req.files.upfile;' + "\n",
        '        <span style="color:#000099;">var</span> dir = me.paths.<span style="color:#000099;">public</span> + <span style="color:#009900;">\'/upload/\'</span>;' + "\n",
        '        NX.Fs.rename(' + "\n",
        '            upfile.path,' + "\n",
        '            dir + upfile.name,' + "\n",
        '            <span style="color:#000099;">function</span> (err) {' + "\n",
        '                <span style="color:#000099;">if</span>(err) {' + "\n",
        '                    <span style="color:#000099;">throw</span> err;' + "\n",
        '                }' + "\n",
        '                me.<span style="color:#000099;">set</span>(<span style="color:#009900;">\'upfilename\'</span>, upfile.name);' + "\n",
        '                me.end();' + "\n",
        '            }' + "\n",
        '        );' + "\n",
        '    }' + "\n",
        '}];',
        '</pre>',

        '<p>',
        '<em>this.req.files</em>にアップロードされたファイル情報が格納されています。',
        'アップロードフォームでつけた名前をキーに、アップロードファイルの情報を取得しましょう。',
        '先ほどフォームでは、<em>upfile</em>という名前でアップロードするようにしましたので、<em>this.req.files.upfile</em>',
        'でアクセスします。',
        '<em>this.req.files.upfile.path</em>に実際にアップロードされたディレクトリが格納されています。',
        'なので、任意のディレクトリ(上記では、publicディレクトリ下のuploadディレクトリに格納)に移動します。',
        '例で使用している、NX.Fs.renameはnodeのrequire(\'fs\')をラッピングしたクラスです。',
        'アップロード完了後に、upfilenameというキーでテンプレートのアップロードしたファイル名を出力します。',
        '</p>',

        '<h4>upload.html</h4>',
        '<pre>',
        '<span style="color:#0000FF;">&lt;html&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;head&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;meta <span style="color:#000000;">http-equiv=</span><span style="color:#009900;">&quot;Content-Type&quot;</span> <span style="color:#000000;">content=</span><span style="color:#009900;">&quot;text/html; charset=utf8&quot;</span>&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;title&gt;</span>Next JS UPLOADテスト<span style="color:#0000FF;">&lt;/title&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/head&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;body&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;h2&gt;</span>Upload<span style="color:#0000FF;">&lt;/h2&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;p&gt;</span>アップロードされたファイル<span style="color:#0000FF;">&lt;/p&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;p&gt;</span><span style="color:#990000;">&lt;!--{upfilename}--&gt;</span><span style="color:#0000FF;">&lt;/p&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/body&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/html&gt;</span>',
        '</pre>',

        '<address>Copyright &copy; 2006 - 2011 <a href="http://www.xenophy.com/">Xenophy.CO.,LTD</a> All rights Reserved.</address>',

        ].join("")
    });
