Ext.data.JsonP.tutorial_action({
    "guide": [

        '<h1>アクションとアクションチェーン</h1>',
        '<p>',
        'サーバーを起動して、HTMLを表示できる状態になると、同時にアクションを実行することができる環境が整っています。',
        'まずは、HTML、そしてアクションをまとめて<em>仮想スクリーン</em>という考え方で表示されていることを説明します。',
        '</p>',

        '<h2>仮想スクリーン</h2>',
        '<p>',
        '仮想スクリーンとは、１ページ１ページの表示を行うための画面とのことを指します。',
        '例えば、index.htmlというページを一つの仮想スクリーンと考えることができます。',
        '仮想スクリーンは、<em>アクション</em>と呼ばれる処理単位が存在し、<em>public</em>ディレクトリに静的HTMLを配置して',
        'アクセスした場合は、アクションは何も処理されずHTMLが表示されます。',
        '<em>アクションは、後から開発者が差し込んで行くもの</em>です。',
        'もちろん、慣れてきて先にアクションを記述することも可能です。',
        'このとき、最終的に出力されるHTMLは、内部的にテンプレートとして扱われます。',
        '</p>',
        '<p>',
        '仮想スクリーンは、言わば<em>アクション+テンプレート</em>であるといえます。',
        '</p>',

        '<h3>仮想スクリーンがあることによって、何がうれしいか。</h3>',
        '<p>',
        '通常のMVCフレームワークの場合、開発者がコントローラーをアクセスされるファイルに記述するところから、作業を始まります。',
        'Next JSのフレームワーク機能は、Next JSがURLを元に内部でコントローラーを自動的に生成して、アクションを実行、',
        'そして、最終的にテンプレートを出力します。',
        '自動的にHTMLがテンプレートとして出力されるため、まずHTMLから作成し始めることができます。',
        'つまり、プログラマではなくWebデザイナー（またはHTMLコーダー）が、まずファイルを配置してモック版のシステム、サイトを構築することができます。',
        'プログラマは、後から必要な箇所に必要なだけアクションを差し込んでいき、',
        'HTMLが表示されるよりも前の処理を記述していきます。',
        '</p>',

        '<h3>ファイル名はアクション名</h3>',
        '<p>',
        '仮想スクリーンは、アクセスされたURLのファイル名を<em>アクション名</em>として認識します。',
        '<em>index.html</em>, <em>index.js</em>, <em>index.jpg</em>、これらは、すべて<em>index</em>というアクション名になります。',
        '認識したアクション名を元にアクションを実行して、テンプレートを出力します。',
        'アクションは、任意の処理を行い、テンプレートへ渡すことができます。',
        '単純なHTMLでも、テンプレートタグさえ記載すれば、変数の埋め込みや繰り返しが簡単に行うことができます。',
        '</p>',


        '<h2>アクションを記述する</h2>',
        '<p>',
        'まずは、index.htmlを配置して、indexアクションを実行するための、アクションファイルを記述します。',
        'アクションファイルは、server.jsと同じディレクトリに<em>actions</em>というディレクトリに下に作成します。',
        '<em>public</em>と<em>actions</em>のディレクトリ構造は、同じディレクトリ階層として扱われます。',
        '<em>foo/index.html</em>のindexアクションの場合、actions以下に、<em>foo/index.js</em>を作成することになります。',
        '</p>',
        '<p>',
        'actionsディレクトリ下に、index.jsを作成します。',
        '</p>',

        '<pre>',
        'module.exports = {' + "\n",
        '    execute: <span style="color:#000099;">function</span>() {' + "\n",
        '        <span style="color:#000099;">this</span>.<span style="color:#000099;">set</span>(<span style="color:#009900;">\'mykey\'</span>, <span style="color:#009900;">\'myvalue\'</span>);' + "\n",
        '        <span style="color:#000099;">this</span>.end();' + "\n",
        '    }' + "\n",
        '};' + "\n",
        '</pre>',

        '<p>',
        '次に、publicディレクトリ下にindex.htmlを作成します。',
        '</p>',

        '<pre>',
        '<span style="color:#0000FF;">&lt;html&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;head&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;meta <span style="color:#000000;">http-equiv=</span><span style="color:#009900;">&quot;Content-Type&quot;</span> <span style="color:#000000;">content=</span><span style="color:#009900;">&quot;text/html; charset=utf8&quot;</span>&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;title&gt;</span>Next JS HTML表示テスト<span style="color:#0000FF;">&lt;/title&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/head&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;body&gt;</span>' + "\n",
        '    <span style="color:#0000FF;">&lt;p&gt;</span>mykeyの値:<span style="color:#990000;">&lt;!--{mykey}--&gt;</span><span style="color:#0000FF;">&lt;/p&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/body&gt;</span>' + "\n",
        '<span style="color:#0000FF;">&lt;/html&gt;</span>' + "\n",
        '</pre>',

        '<p>',
        '早速、ブラウザからindex.htmlにアクセスしてみましょう。',
        '</p>',

        '<pre>',
        'mykeyの値:myvalue',
        '</pre>',

        '<p>',
        '&lt;!--{mykey}--&gt;の部分が<em>myvalue</em>になっています',
        'これでアクションが実行されていることが確認できました。',
        'では、index.jsの中を見ていきましょう。',
        '</p>',
        '<p>',
        'moduke.exportsにオブジェクトリテラルでアクションを定義しています。',
        'このオブジェクトリテラルに、<em>execute</em>というキーを作成して、そこに関数オブジェクトを指定します。',
        'これで該当のアクション名が指定されたときに、executeに指定した関数オブジェクトが呼びされるようになります。',
        'このexecuteに指定した関数オブジェクトをexecuteメソッドと呼びます。',
        'executeメソッドは、必ず<em>this.end();</em>を呼び出す必要があります。',
        'これは、ほとんどの場合nodeでプログラムを記述するとコールバック関数により処理が記載されるため、',
        'executeメソッドが同期的に終了したからといって、開発者が意図するタイミングで終了となるわけではないため、',
        '開発者が明示的に終了ポイントを定義する必要があります。',
        '</p>',
        '<p>',
        'さらに<em>this.set([key], [value]);</em>、を呼び出すことで、アクション内での処理結果を、テンプレートに引き渡すことができます。',
        '</p>',


        '<address>Copyright &copy; 2006 - 2011 <a href="http://www.xenophy.com/">Xenophy.CO.,LTD</a> All rights Reserved.</address>',

    ].join("")
});
